name: Tests

on:
  pull_request:
  push:
    branches-ignore:
      - main

jobs:
  backend-tests:
    name: Backend tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install backend dependencies
        working-directory: apps/backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run backend tests
        working-directory: apps/backend
        run: |
          pytest --maxfail=1 --disable-warnings --cov=app --cov-report=term-missing

  web-tests:
    name: Web tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install web dependencies
        working-directory: apps/web
        run: |
          npm install --no-audit --no-fund

      - name: Run web tests
        working-directory: apps/web
        env:
          CI: "true"
        run: |
          npm test -- --runInBand --ci
